import path from "node:path";

import { defineConfig } from "orval";

/**
 * Orval configuration for Datto RMM API, Datto RMM v10.8.0.
 *
 * Two targets over the same PATCHED spec (mirrors fuze-api):
 *
 * 1. 'datto' (client: 'axios'):
 *    - Generates TypeScript types in src/generated/types/ (the only product of this
 *      target the client consumes).
 *    - Also emits an endpoints layer under src/generated/endpoints/ — this is a
 *      transient, git-ignored artifact (see .gitignore); resources hand-write their
 *      paths as the single source of truth, so the endpoints file is never imported.
 *    - No mutator: the shared, interceptor-bearing axios instance is built directly
 *      in src/http/http-client.ts (Phase 5), not generated by Orval.
 *
 * 2. 'dattoZod' (client: 'zod'):
 *    - Generates Zod v4 validation schemas in src/generated/schemas/<tag>/<tag>.zod.ts.
 *    - Responses are non-strict (unknown keys tolerated by the generated schema itself;
 *      further leniency — nullability, enum widening — is layered on in
 *      src/validation/schema-leniency.ts). Bodies/params/query/headers are strict.
 *    - Dates coerced across body/response/param/query.
 *
 * Input is the PATCHED spec (spec/openapi.patched.json), produced by
 * scripts/patch-spec.mjs from the committed spec/openapi.json (Phase 2). Overridable via
 * DATTO_OPENAPI_SPEC for local experimentation.
 *
 * Both targets set `output.clean: true`: Orval only ever writes the files a given generation
 * pass actually produces, so if a spec refresh removes a component schema (or patch-spec.mjs's
 * own alertContext correction prunes now-dead components — see patch-spec.mjs's
 * `pruneOrphanedContextSchemas`), the type/schema files that schema used to generate are
 * silently left behind on disk, stale and unreferenced, rather than deleted. `clean: true` makes
 * `npm run generate` remove every non-`.d.ts` file under each target's output directory before
 * writing, so the committed `src/generated/**` always reflects exactly the current patched spec
 * — never a superset accumulated across regenerations.
 */
const spec =
  process.env.DATTO_OPENAPI_SPEC ??
  path.resolve(__dirname, "./spec/openapi.patched.json");

export default defineConfig({
  datto: {
    input: { target: spec },
    output: {
      mode: "tags-split",
      target: "./src/generated/endpoints/api.ts",
      schemas: "./src/generated/types",
      client: "axios",
      clean: true,
    },
  },
  dattoZod: {
    input: { target: spec },
    output: {
      mode: "tags-split",
      client: "zod",
      target: "./src/generated/schemas/api.zod.ts",
      fileExtension: ".zod.ts",
      clean: true,
      override: {
        zod: {
          strict: {
            response: false,
            body: true,
            param: true,
            query: true,
            header: true,
          },
          generate: {
            body: true,
            response: true,
            query: true,
            param: true,
            header: true,
          },
          coerce: {
            body: ["date"],
            response: ["date"],
            param: ["date"],
            query: ["date"],
          },
        },
      },
    },
  },
});
